version: '3'
services:
  ui:
    image: 'shaun210/multi-frontend'
    mem_limit: 128m
    hostname: ui
    environment:
      - NODE_ENV=production
  backend-server:
    image: 'shaun210/multi-backend'
    mem_limit: 128m
    hostname: backend-server
    environment:
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  nginx:
    image: 'shaun210/multi-nginx'
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
