const WEBSOCKET_URLS = {
    development: 'ws://localhost:8080/gs-guide-websocket',
    production: 'ws://find-gym-partner-env.eba-8tda8qu8.us-east-1.elasticbeanstalk.com/gs-guide-websocket',
};


const API_URLS = {
    development: 'http://localhost:8080/',
    production: 'http://find-gym-partner-env.eba-8tda8qu8.us-east-1.elasticbeanstalk.com/api/',
};
  
const environment = process.env.NODE_ENV || 'development';
  
export const onlineAPI = API_URLS[environment];
export const websocketURL = WEBSOCKET_URLS[environment];

export const paths = {
    HOME: '/',
    FRIEND_LIST: '/friendList',
    LOGIN: '/login',
    SINGLE_CHAT: '/singleChat/:friendName',
    SIGNIN: '/signin',
    FIND_PEOPLE: '/findPeople',
    EDIT_PROFILE: '/editProfile',
    PROFILE: '/profile/:username',
}

export const listOfAddress = {
    "Alberta": [
        "Airdrie",
        "Beaumont",
        "Brooks",
        "Calgary",
        "Chestermere",
        "Cold Lake",
        "Edmonton",
        "Fort Saskatchewan",
        "Grande Prairie",
        "Lacombe",
        "Leduc",
        "Lethbridge",
        "Lloydminster (part)",
        "Medicine Hat",
        "Red Deer",
        "Spruce Grove",
        "St. Albert",
        "Wetaskiwin"
    ],
    "British Columbia": [
        "Abbotsford",
        "Armstrong",
        "Burnaby",
        "Campbell River",
        "Castlegar",
        "Chilliwack",
        "Colwood",
        "Coquitlam",
        "Courtenay",
        "Cranbrook",
        "Dawson Creek",
        "Delta",
        "Duncan",
        "Enderby",
        "Fernie",
        "Fort St. John",
        "Grand Forks",
        "Greenwood",
        "Kamloops",
        "Kelowna",
        "Kimberley",
        "Langford",
        "Langley",
        "Maple Ridge",
        "Merritt",
        "Mission",
        "Nanaimo",
        "Nelson",
        "New Westminster",
        "North Vancouver",
        "Parksville",
        "Penticton",
        "Pitt Meadows",
        "Port Alberni",
        "Port Coquitlam",
        "Port Moody",
        "Powell River",
        "Prince George",
        "Prince Rupert",
        "Quesnel",
        "Revelstoke",
        "Richmond",
        "Rossland",
        "Salmon Arm",
        "Surrey",
        "Terrace",
        "Trail",
        "Vancouver",
        "Vernon",
        "Victoria",
        "West Kelowna",
        "White Rock",
        "Williams Lake"
    ],
    "Manitoba": [
        "Brandon",
        "Dauphin",
        "Flin Flon (part)",
        "Morden",
        "Portage la Prairie",
        "Selkirk",
        "Steinbach",
        "Thompson",
        "Winkler",
        "Winnipeg"
    ],
    "New Brunswick": [
        "Bathurst",
        "Campbellton",
        "Dieppe",
        "Edmundston",
        "Fredericton",
        "Miramichi",
        "Moncton",
        "Saint John"
      ],
      "Newfoundland and Labrador": [
        "Corner Brook",
        "Mount Pearl",
        "St. John's"
      ],
    'Nova Scotia': [
        'Halifax',
        'Sydney',
        'Dartmouth',
    ],
    "Ontario": [
        "Barrie",
        "Belleville",
        "Brampton",
        "Brant",
        "Brantford",
        "Brockville",
        "Burlington",
        "Cambridge",
        "Clarence-Rockland",
        "Cornwall",
        "Dryden",
        "Elliot Lake",
        "Greater Sudbury",
        "Guelph",
        "Haldimand County",
        "Hamilton",
        "Kawartha Lakes",
        "Kenora",
        "Kingston",
        "Kitchener",
        "London",
        "Markham",
        "Mississauga",
        "Niagara Falls",
        "Norfolk County",
        "North Bay",
        "Orillia",
        "Oshawa",
        "Ottawa",
        "Owen Sound",
        "Pembroke",
        "Peterborough",
        "Pickering",
        "Port Colborne",
        "Prince Edward County",
        "Quinte West",
        "Richmond Hill",
        "Sarnia",
        "Sault Ste. Marie",
        "St. Catharines",
        "St. Thomas",
        "Stratford",
        "Temiskaming Shores",
        "Thorold",
        "Thunder Bay",
        "Timmins",
        "Toronto",
        "Vaughan",
        "Waterloo",
        "Welland",
        "Windsor",
        "Woodstock"
      ],
    'Prince Edward Island': [
        'Charlottetown',
        'Summerside',
    ],
    "Quebec": [
        "Montreal",
        "Quebec City (Ville de Québec)",
        "Laval",
        "Gatineau",
        "Longueuil",
        "Sherbrooke",
        "Saguenay",
        "Levis (Lévis)",
        "Trois-Rivières",
        "Terrebonne",
        "Saint-Jean-sur-Richelieu",
        "Repentigny",
        "Brossard",
        "Drummondville",
        "Saint-Jérôme",
        "Granby",
        "Blainville",
        "Saint-Hyacinthe",
        "Shawinigan",
        "Dollard-des-Ormeaux"
      ],
    "Saskatchewan": [
        "Estevan",
        "Flin Flon",
        "Humboldt",
        "Lloydminster",
        "Martensville",
        "Meadow Lake",
        "Melfort",
        "Melville",
        "Moose Jaw",
        "North Battleford",
        "Prince Albert",
        "Regina",
        "Saskatoon",
        "Swift Current",
        "Warman",
        "Weyburn",
        "Yorkton"
      ],
    'Northwest Territories': [
        'Yellowknife',
        'Inuvik',
    ],
    'Nunavut': [
        'Iqaluit',
        'Rankin Inlet',
    ],
    'Yukon': [
        'Whitehorse',
        'Dawson City',
    ]
};
