name: Deploy MultiDocker
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t shaun210/multi-frontend ./frontend
      - run: docker build -t shaun210/multi-backend ./backend
      - run: docker build -t shaun210/multi-nginx ./nginx

      - run: docker push shaun210/multi-frontend
      - run: docker push shaun210/multi-backend
      - run: docker push shaun210/multi-nginx

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: find-gym-partner
          environment_name: Find-gym-partner-env
          existing_bucket_name: elasticbeanstalk-us-east-1-891377082988 
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip

